// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lua.proto

#ifndef PROTOBUF_lua_2eproto__INCLUDED
#define PROTOBUF_lua_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_lua_2eproto();
void protobuf_AssignDesc_lua_2eproto();
void protobuf_ShutdownFile_lua_2eproto();

class proto_lua;

// ===================================================================

class proto_lua : public ::google::protobuf::Message {
 public:
  proto_lua();
  virtual ~proto_lua();
  
  proto_lua(const proto_lua& from);
  
  inline proto_lua& operator=(const proto_lua& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const proto_lua& default_instance();
  
  void Swap(proto_lua* other);
  
  // implements Message ----------------------------------------------
  
  proto_lua* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proto_lua& from);
  void MergeFrom(const proto_lua& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  
  // optional string sex = 2;
  inline bool has_sex() const;
  inline void clear_sex();
  static const int kSexFieldNumber = 2;
  inline const ::std::string& sex() const;
  inline void set_sex(const ::std::string& value);
  inline void set_sex(const char* value);
  inline void set_sex(const char* value, size_t size);
  inline ::std::string* mutable_sex();
  
  // optional int32 age = 3;
  inline bool has_age() const;
  inline void clear_age();
  static const int kAgeFieldNumber = 3;
  inline ::google::protobuf::int32 age() const;
  inline void set_age(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:proto_lua)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::std::string* name_;
  static const ::std::string _default_name_;
  ::std::string* sex_;
  static const ::std::string _default_sex_;
  ::google::protobuf::int32 age_;
  friend void  protobuf_AddDesc_lua_2eproto();
  friend void protobuf_AssignDesc_lua_2eproto();
  friend void protobuf_ShutdownFile_lua_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static proto_lua* default_instance_;
};
// ===================================================================


// ===================================================================

// proto_lua

// optional string name = 1;
inline bool proto_lua::has_name() const {
  return _has_bit(0);
}
inline void proto_lua::clear_name() {
  if (name_ != &_default_name_) {
    name_->clear();
  }
  _clear_bit(0);
}
inline const ::std::string& proto_lua::name() const {
  return *name_;
}
inline void proto_lua::set_name(const ::std::string& value) {
  _set_bit(0);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void proto_lua::set_name(const char* value) {
  _set_bit(0);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void proto_lua::set_name(const char* value, size_t size) {
  _set_bit(0);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* proto_lua::mutable_name() {
  _set_bit(0);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  return name_;
}

// optional string sex = 2;
inline bool proto_lua::has_sex() const {
  return _has_bit(1);
}
inline void proto_lua::clear_sex() {
  if (sex_ != &_default_sex_) {
    sex_->clear();
  }
  _clear_bit(1);
}
inline const ::std::string& proto_lua::sex() const {
  return *sex_;
}
inline void proto_lua::set_sex(const ::std::string& value) {
  _set_bit(1);
  if (sex_ == &_default_sex_) {
    sex_ = new ::std::string;
  }
  sex_->assign(value);
}
inline void proto_lua::set_sex(const char* value) {
  _set_bit(1);
  if (sex_ == &_default_sex_) {
    sex_ = new ::std::string;
  }
  sex_->assign(value);
}
inline void proto_lua::set_sex(const char* value, size_t size) {
  _set_bit(1);
  if (sex_ == &_default_sex_) {
    sex_ = new ::std::string;
  }
  sex_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* proto_lua::mutable_sex() {
  _set_bit(1);
  if (sex_ == &_default_sex_) {
    sex_ = new ::std::string;
  }
  return sex_;
}

// optional int32 age = 3;
inline bool proto_lua::has_age() const {
  return _has_bit(2);
}
inline void proto_lua::clear_age() {
  age_ = 0;
  _clear_bit(2);
}
inline ::google::protobuf::int32 proto_lua::age() const {
  return age_;
}
inline void proto_lua::set_age(::google::protobuf::int32 value) {
  _set_bit(2);
  age_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_lua_2eproto__INCLUDED
